# Generated by Django 2.1.3 on 2018-11-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(),
        ),
    ]
