# Generated by Django 2.1.3 on 2018-11-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appable', '0002_auto_20181110_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainline',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='release',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='releasefiles',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
