# Generated by Django 2.1.3 on 2018-11-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appable', '0004_auto_20181110_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='releasefile',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appable.ReleaseFileType'),
            preserve_default=False,
        ),
    ]
