# Generated by Django 2.1.3 on 2018-11-10 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appable', '0005_auto_20181110_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainline',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
