# Generated by Django 3.0.3 on 2020-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsmine', '0002_auto_20181217_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownedmainline',
            options={'ordering': ['owned_product__group__name', 'owned_product__product__name', 'mainline__name']},
        ),
        migrations.AlterModelOptions(
            name='ownedproduct',
            options={'ordering': ['group__name', 'product__name']},
        ),
        migrations.AlterField(
            model_name='ownedproduct',
            name='purchased_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ownedproduct',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
